// Date: 4/28/2015 9:53:19 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package org.bitbucket.alltra101ify.advancedsatelliteutilization.models.blockmodel;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCoreGenerator extends ModelBase
{
  //fields
    ModelRenderer BaseB;
    ModelRenderer BaseT;
    public ModelRenderer MainCrystal;
  
  public ModelCoreGenerator()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      BaseB = new ModelRenderer(this, 0, 18);
      BaseB.addBox(0F, 0F, 0F, 16, 2, 16);
      BaseB.setRotationPoint(-8F, 8F, -8F);
      BaseB.setTextureSize(128, 128);
      BaseB.mirror = true;
      setRotation(BaseB, 0F, 0F, 0F);
      BaseT = new ModelRenderer(this, 0, 0);
      BaseT.addBox(0F, 0F, 0F, 16, 2, 16);
      BaseT.setRotationPoint(-8F, 22F, -8F);
      BaseT.setTextureSize(128, 128);
      BaseT.mirror = true;
      setRotation(BaseT, 0F, 0F, 0F);
      MainCrystal = new ModelRenderer(this, 64, 0);
      MainCrystal.addBox(-4F, -4F, -4F, 8, 8, 8);
      MainCrystal.setRotationPoint(0F, 16F, 0F);
      MainCrystal.setTextureSize(128, 128);
      MainCrystal.mirror = true;
      setRotation(MainCrystal, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    BaseB.render(f5);
    BaseT.render(f5);
    MainCrystal.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void renderModel(float f) {
	    BaseB.render(f);
	    BaseT.render(f);
	    MainCrystal.render(f);
}
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
